### ISSUE TITLE
Adding/Editing the default file doesn't update WebView

### ISSUE THREAD

**Issue by JonLevin25** [usernamehw/vscode-todo-md#29]
When editing the default file's text directly, the WebView doesn't update.
Closing/Opening the Webview won't update either, but **Toggling a task's completion** (in the WebView) will force a refresh.

Repro:
1. Open WebView
2. Open defualt file (text)
3. Add a task, save
4. Expected: WebView updates with new task, Actual: Nothing happens
5. Close/Open WebView - doesn't update either
6. Toggle completion (of any task) in WebView - it updates that task as well as adding your new task

![image](https://user-images.githubusercontent.com/57547561/120598139-9159b280-c44e-11eb-8fbe-ba078e0fff8b.png)

**Comment by usernamehw** [comment]
I assume this is the same problem as #30.
