### ISSUE TITLE
Syntax Highlighting not working

### ISSUE THREAD

**Issue by JonLevin25** [usernamehw/vscode-todo-md#30]
Hi,
Not sure if this is an issue with Todo MD or something else - but I can't seem to get syntax highlighting to work?
I set `todo.md` as my default file, and it shows up in the webview/changes are synced, but there's no syntax highlighting at all in the text file.

Also, not sure if this is related, But the webview doesn't update when I edit the default file also, I've opened a separate ticket for that
https://github.com/usernamehw/vscode-todo-md/issues/29

![image](https://user-images.githubusercontent.com/57547561/120598074-7edf7900-c44e-11eb-9179-7acc13fcb540.png)

**Comment by usernamehw** [comment]
Does it make any difference if the file is named `todo.md` (lowercase)?

**Comment by JonLevin25** [comment]
Changing the case didnt work because NTFS\Windows is case-insensitive so the old name seemed to be cached

But adding "TODO" to the glob pattern worked! That seemed to be the issue, thanks :)

Maybe the default on windows should be making this case insensitive? I think glob behaves that way by default in some languages.

**Comment by usernamehw** [comment]
This extension is using built-in vscode api and in vscode Glob matching is case-sensitive https://github.com/microsoft/vscode/issues/10633. 
I don't think it's something that makes it worth of importing another library.
