### ISSUE TITLE
Views are rendered differently when not editing todo.md

### ISSUE THREAD

**Issue by meanderix** [usernamehw/vscode-todo-md#31]
When I edit todo.md, the webview correctly shows a nested treeview with all the tasks. However, when editing some other file the view is rendered incorrectly with all projects/contexts/tags being shown at the top and then all the tasks being shown without any nesting at all. The tasks view seem to follow a similar pattern with nesting and indentation of subitems being disabled when switching to a different file.

**Comment by usernamehw** [comment]
Do you have `todomd.defaultFile` set? Any specific steps to reproduce? A screenshot or a gif might help also.

**Comment by usernamehw** [comment]
Actually it might be because of the indent size. Do you use tabs or 2 spaces? When editor is not opened extension can't determine it.

If you use spaces, would it change with this setting:

```js
"todomd.tabSize": 2,
```

**Comment by meanderix** [comment]
![image](https://user-images.githubusercontent.com/4612502/124098206-a2511000-da5c-11eb-94c5-5f1ae474373f.png)
Here's a side-by-side comparison. I'll take a look at `todomd.tabSize`. Yes, I have a `todomd.defaultFile` set.

**Comment by meanderix** [comment]
Nope, `todomd.tabSize` didn't help.

**Comment by meanderix** [comment]
Yes! `todomd.tabSize` did help! I'm not sure I understand the logic here though. :)

**Comment by usernamehw** [comment]
To determine if the task is nested I need to know what indentation is used in the file. TextEditor has `tabSize`:

https://code.visualstudio.com/api/references/vscode-api#TextEditorOptions

But I can only know it if the file is opened in the editor.

Default indent in markdown is 4 spaces I think.

**Comment by usernamehw** [comment]
Have nothing planned for this ATM.
