### ISSUE TITLE
Add simple text?

### ISSUE THREAD

**Issue by dalmo3** [usernamehw/vscode-todo-md#34]
Is it possible to add common text to the file without the extension parsing every new line as a separate task? Even comments are parsed as tasks.

```
(A) ☐ task such and such
       this task is about ....
```

**Comment by usernamehw** [comment]
This extension is built around it (1 line - 1 task). If you want to make a comment - replace comment hotkey when inside todo file:

```js
{
    "key": "ctrl+/",
    "command": "todomd.toggleComment",
    "when": "editorFocus && todomd:isActive"
},
```

**Comment by dalmo3** [comment]
That works great, thank you.

I had only tried the other comment syntax, `<!--- ... -->`, when I wrote that.

Thanks for the awesome extension!
