### ISSUE TITLE
Honor #, @, and + tags position within todo item text

### ISSUE THREAD

**Issue by Scott-Thomas** [usernamehw/vscode-todo-md#36]
This could be nitpicky, but I like to use `@context`, `#tag` and `+project` attributes _within_ the body text of my todo items. However the extension automatically moves any attributes to the end of the line.

For example, the todo item: `Move +Project items to other #buckets` would render as: `Move items to other #buckets +Project ` (which admittedly, while not perfect, is comprehensible).

But, since I like to use the `@context` attribute for colleagues' names, the item: `Speak to @Context about +Project #issue`. becomes; `Speak to about #issue +Project @Context`, which is a bit harder to parse than the original.

Is it possible to override this automatic attribute repositioning? It's probably a trivial change if you know CSS (or JS?) but unfortunately I don't.

If not, is it possible to have an override option added?

**Comment by usernamehw** [comment]
Yes, it should be the default to honor the position.

There are probably 3 different places in code that move the text with different logic: 1) Tree View 2) Webview 3) Editor hover / Tree View Hover.

**Comment by usernamehw** [comment]
It should work in **2.9.0**.
