### ISSUE TITLE
Tags/contexts/projects not rendering in Task view

### ISSUE THREAD

**Issue by Scott-Thomas** [usernamehw/vscode-todo-md#37]
I've encountered a bug in this extension that causes any contexts, tags, or projects to not render correctly in the Tasks view.

Here is a screenshot of the problem:
![Screenshot-bad](https://user-images.githubusercontent.com/12754488/138990728-7554e5a1-c719-46e9-a27d-7a558ab31a8e.png)

* Version: 1.61.2
* Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
* Date: 2021-10-19T14:58:13.605Z
* Electron: 13.5.1
* Chrome: 91.0.4472.164
* Node.js: 14.16.0
* V8: 9.1.269.39-electron.0
* OS: Linux x64 4.19.0-18-amd64
* TodoMD version: v2.8.2

Here is the same Task view rendered correctly.

![Screenshot-good](https://user-images.githubusercontent.com/12754488/138990730-4a4a7d87-6662-46a2-98a1-7c82d5b6cd6a.png)

* Version: 1.61.2
* Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
* Date: 2021-10-19T14:58:13.605Z
* Electron: 13.5.1
* Chrome: 91.0.4472.164
* Node.js: 14.16.0
* V8: 9.1.269.39-electron.0
* OS: Linux x64 5.4.0-89-generic
* TodoMD version: v2.8.2

Everything looks fine in the Webview on both distros.

As mentioned in my previous issue, I'm not very well versed in CSS/JS etc. I have Googled the issue extensively, and tried some of the various fixes I've found, but haven't found a solution yet.

Any help would be appreciated.

**Comment by usernamehw** [comment]
Tree views don't support Bold/Italic, or ... anything. But there are hacks to use different symbols, like https://yaytext.com/bold-italic/

That's basically what this extension is trying to do:

https://github.com/usernamehw/vscode-todo-md/blob/2dc37ae675c858dbd2d2e50b00df694acbd05280/src/utils/utils.ts#L18-L46

Looks like this:
<img width="600" src="https://user-images.githubusercontent.com/9638156/141651501-c3166644-4f24-4ea1-b82b-486095f5df9b.png">

I'm thinking of adding a setting to disable this hack.

**Comment by usernamehw** [comment]
From the next extension version:

```js
"todomd.useBoldTextInLabels": false,
```
