### ISSUE TITLE
Parse tags like {due:fri} written inside double quote maks

### ISSUE THREAD

**Issue by ezececi** [usernamehw/vscode-todo-md#38]
My use case is that I already use .ipynb file for my todo lists, and more precisely I use markdown cell inside ,ipynb files.
The formatting of ipynb files put the content of my todo inside double mark quotes, see example below. Todo MD does not parse the text inside quotes.

Example of a todo,ipynb file with the following content inside the markdown cell : 
```
# Todo
- todo1
- todo2
```
Content of the todo.ipynb file :
```
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Todo\n",
    "- todo1\n",
    "- todo2"
   ]
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1"
  },
  "kernelspec": {
   "display_name": "Python 3.8.10 64-bit",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.8.10"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

**Comment by usernamehw** [comment]
No plans.
