### ISSUE TITLE
Filter by tasks NOT done

### ISSUE THREAD

**Issue by razovsuki** [usernamehw/vscode-todo-md#39]
I was suprised to see that, as far as I can tell, there is no way to filter the webview or any other view to only show the tasks that aren't marked as done. You can filter by "done", but not by "not done", or did I miss a feature?
As I go through the tasks and mark them as done, I would like them to not appear in the list, hence the need for this filter.
Would it be possible to add?
Thanks!

**Comment by razovsuki** [comment]
My bad, I just realised that there is a setting to hide the done tasks in the Webview. Wouldn't it make more sense as a filter though? I like the flexibility of being able to show or hide them just by using the filter, instead of having to toggle the setting on or off.

**Comment by usernamehw** [comment]
`-$done` ?

**Comment by razovsuki** [comment]
Yep, I knew I was missing something. I tried `!`. I tried `NOT`. It was `-` 😅 
Thanks for the help!
