### ISSUE TITLE
please add support to ignore markdown frontmatter

### ISSUE THREAD

**Issue by Neil2893** [usernamehw/vscode-todo-md#40]
please add support to ignore markdown frontmatter

**Comment by Neil2893** [comment]
hi, I took care of the problem myself. would you like a pull request?

**Comment by usernamehw** [comment]
If it's a simple change that doesn't introduce a 200Kb dependency like https://www.npmjs.com/package/front-matter or https://www.npmjs.com/package/gray-matter then - yes.
