### ISSUE TITLE
more sorting options

### ISSUE THREAD

**Issue by np-trivial** [usernamehw/vscode-todo-md#43]
as a convert from [todotxt](https://github.com/davraamides/todotxt-mode) , I miss some of the sorting choices. Here are some of the ideas I'd request being able to configure

- [x] tasks with no due date get sorted after those with future due dates
- [ ] priority tasks go above due date tasks
- [x] sort by due date
- [x] sort by completion date
- [x] sort by creation date
- [x] sort by project
- [x] sort by tag
- [x] sort by context

**Comment by daniel-wojcik** [comment]
I miss one basic/must-have sorting command which sorts completed tasks after active, for example:

Before:
```
Done {cm}
Active
```

After:

```
Active
Done {cm}
```

Sort by Completion Date ignores task completed but without date specified like above.

**Comment by usernamehw** [comment]
Closing as most sorting items implemented. "Priority above Due" not planned.
