### ISSUE TITLE
How to create custom priority?

### ISSUE THREAD

**Issue by Creveoolus** [usernamehw/vscode-todo-md#48]
I wanna make a custom priority like (A) or (B). 
It should be (BUG) and (FEATURE).

Can i implement this in settings.json? If I do, then how?

**Comment by usernamehw** [comment]
It's not supported.

But this example it looks like `BUG` and `FEATURE` are more of a category than a priority. Like, you would have multiple bugs and features and they would use a context `@bug` or tag `#bug`:

```
(A) fix that thing @bug
(B) fix another thing @bug

(A) implement something @feature
(B) implement another thing @feature
```

**Comment by Creveoolus** [comment]
thanks
