### ISSUE TITLE
Webview search prompt list: highlighted element poorly visible

### ISSUE THREAD

**Issue by daniel-wojcik** [usernamehw/vscode-todo-md#49]
When searching for tag/context/project using webview search box highlighted element in the list is poorly visible because of using similar (if not the same) colors for highlight matching part of text and highlight of the list row:
![TODO-1](https://user-images.githubusercontent.com/8803692/173117900-8dac650d-a12c-43f6-85c2-7f5c2a292d01.png)
.

**Comment by usernamehw** [comment]
I think it uses colors from the active theme - `--vscode-editorSuggestWidget-highlightForeground` for match and `--vscode-editorSuggestWidget-selectedBackground` to look similar to the editor suggest widget.

Is it default light color theme? Does suggest widget in editor also look that bad?

**Comment by usernamehw** [comment]
Actually, there's another variable `--vscode-editorSuggestWidget-focusHighlightForeground` for this case.
