### ISSUE TITLE
Set task completed/active commands request

### ISSUE THREAD

**Issue by daniel-wojcik** [usernamehw/vscode-todo-md#52]
It would be good to have possibility of setting current task as completed or as active by the command(s). Now there is a command **Complete a Task** which is not useful (especially for many active tasks) because it displays a list of active tasks. It is completely unnecessary and not homogeneous with other commands which operate on current task - so there is already an algorithm which obtains current tasks from cursor position. Also there should be symmetrical command which removes completed element from current task and make it as active.

**Comment by usernamehw** [comment]
There is this command:

`todomd.toggleDone` **Todo MD: Toggle completion**

**Comment by daniel-wojcik** [comment]
Thanks - I didn't notice it.
