### ISSUE TITLE
Nested Tags are not found when using the "Tasks" filter option

### ISSUE THREAD

**Issue by dustinsterk** [usernamehw/vscode-todo-md#55]
I have created a simple example and when filtering the "Tasks" tree view on the tag "#DelegatedActions" nothing shows even though it exists as a nested(using tabs) task/todo.

Ex)
(A) Projects 
    +Personal 
        Cleaning   
            Clean basement   
                Waiting for call back from MikeSmith Cleaners #DelegatedActions

**Comment by usernamehw** [comment]
Yeah, that's one of the basic features that is still not implemented #14

**Comment by dustinsterk** [comment]
Ah I missed that, sorry to cause noise.  This is a great project, if I have time I will look into #14.
