### ISSUE TITLE
todomd.toggleDone trailing space problem

### ISSUE THREAD

**Issue by daniel-wojcik** [usernamehw/vscode-todo-md#56]
This commands adds space at line end while toggle from active to done (before {cm} marker). But it doesn't remove this space on toggling from done to active, it causes the follwing problem:

before:
`Test`

after first alt+d (dot means space):
`Test·{cm:2022-06-23}`

after few more alt+d:
`Test············{cm:2022-06-23}`

**Comment by usernamehw** [comment]
Yeah, I have `"files.trimTrailingWhitespace": true` enabled. 

Maybe other commands have this problem too...
