### ISSUE TITLE
Space added after project or context chosen from prompt list

### ISSUE THREAD

**Issue by daniel-wojcik** [usernamehw/vscode-todo-md#58]
When adding project or context prompt list is shown (if possible). When I choose item from this list (no matter project or context) always space is added after it - which should not be the case. Adding tag this way results with no space added but after any tag superscript is appended with tag's counter. Context and projects has no such superscripts - maybe it is intended, maybe not.

**Comment by usernamehw** [comment]
Are you on the latest version of extension `2.14.0`?

Adding space after context/project/tag autocompleted is expected.

**Comment by daniel-wojcik** [comment]
In fact - after updating to 2.14.0 also projects/contexts started to show number of instances in the file. Thanks for the hint, I didn't expect next version after 2.13.0 so fast.
