### ISSUE TITLE
Sort by priority command places priorities H..Z below already done tasks

### ISSUE THREAD

**Issue by daniel-wojcik** [usernamehw/vscode-todo-md#61]
I expected, than any not done task with any priority always will be placed before done tasks, but if you give task priority from range H..Z it will be placed after done tasks after executing Sort by priority command. It is good that there is range of priorities which are treated as below normal tasks (without priorities) but this range should be like N..Z (second half of alphabet).

**Comment by usernamehw** [comment]
I don't know what you mean. All sorting (except default) is done for 1 field only. It only sorts using one field and ignoring all else.

**Comment by daniel-wojcik** [comment]
Make a file with 4 items: with A priority, with no priority, with Z
priority and done. Then sort by priority - item with Z priority will be
placed at the end, although it is active, so it should be placed before
done task.

sob., 24 wrz 2022, 12:54 użytkownik Alexander ***@***.***>
napisał:

**Comment by usernamehw** [comment]
```
(A)
(F)
completed - irrelevant {cm}
no priority - irrelevant
(G)
(Z)
```

**Comment by daniel-wojcik** [comment]
What does it show? Is it state after sorting by priority?

niedz., 25 wrz 2022, 08:59 użytkownik Alexander ***@***.***>
napisał:

**Comment by daniel-wojcik** [comment]
Ok, I see I need to explain my point: the problem is that I and probably
other users would like to have possibility of such sorting that every done
taskmis placed at the end and not done tasks are placed before in order of
priority. Now I have to apply two command: sort by completion date then
sort by priority. This view in my opinion is the most useful and more often
used one - I don't like when there is mixture done and not done tasks. I
understand that sorting uses only one property and - from formal point of
view you are right. So I propose to introduce special sorting by pair of
properties: done/not done and priority as one command.

niedz., 25 wrz 2022, 09:19 użytkownik Daniel Wójcik ***@***.***>
napisał:

**Comment by usernamehw** [comment]
What if you try to run multiple commands (with the help of extension https://marketplace.visualstudio.com/items?itemName=usernamehw.commands) to run 2 sorts one after another?

**Comment by daniel-wojcik** [comment]
I will check it tomorrow, but probably it will work. Thanks for the hint.

niedz., 25 wrz 2022, 16:15 użytkownik Alexander ***@***.***>
napisał:

**Comment by usernamehw** [comment]
Closing issue as inactive.
