### ISSUE TITLE
Cant find webview

### ISSUE THREAD

**Issue by Creveoolus** [usernamehw/vscode-todo-md#64]
![изображение](https://user-images.githubusercontent.com/48063151/196996556-46801d7e-28bd-4f76-be05-54cae1b4d232.png)
Hello. I started using todomd a long time ago and now when i came back to coding i cant find its webview. It was very helpfull and easy to use but now i cant find it. Could someone pls help?

**Comment by usernamehw** [comment]
It should be inside the TodoMD tree view container by default. Right click on Activity bar to maybe see it if it's hidden.

**Comment by Creveoolus** [comment]
> It should be inside the TodoMD tree view container by default. Right click on Activity bar to maybe see it if it's hidden.

![изображение](https://user-images.githubusercontent.com/48063151/196997782-f59bd667-6cee-4294-9628-5f05463b7329.png)
its not there

**Comment by usernamehw** [comment]
Then you can try to run in Command Palette `View: Reset View Locations` - it will reset all view locations.

**Comment by Creveoolus** [comment]
There it is, thank you alot
