### ISSUE TITLE
Set due date dialog shows wrong interpretation of entered due date

### ISSUE THREAD

**Issue by enicklas** [usernamehw/vscode-todo-md#66]
When setting due dates, the interpretation of the entered due date below the entry field is off by one day. The due date is added correctly to the task, however.

Example for entering relative offset days
![image](https://user-images.githubusercontent.com/53766/199604903-6fad0e32-c0ff-4605-8956-3d7acd054ce5.png)

Example for entering weekday (done on a Wednesday)
![image](https://user-images.githubusercontent.com/53766/199605094-edad039f-e047-47cc-a335-19d23989e87f.png)

**Comment by enicklas** [comment]
PS: Just a guess. This might be due to me using a locale with Monday as the first day of the week (instead of Sunday)

**Comment by usernamehw** [comment]
No, extension is using Monday as the first day of week.

Maybe it was after `00:00`?

**Comment by usernamehw** [comment]
So, it shows this now:

```
Thursday 2022-11-03 [today]  `+2`  =>  Sat 2022-11-03 [in a day]
Thursday 2022-11-03 [today]  `-2`  =>  Tue 2022-11-01 [3 days ago]
```

It's expected to be like this, right?

```
Thursday 2022-11-03 [today]  `+2`  =>  Sat 2022-11-03 [in 2 days]
Thursday 2022-11-03 [today]  `-2`  =>  Tue 2022-11-01 [2 days ago]
```

**Comment by enicklas** [comment]
Perfect, thanks a lot!
