### ISSUE TITLE
Bug: Autocompletion of Tags, Projects and Contexts broken in WebView filter

### ISSUE THREAD

**Issue by enicklas** [usernamehw/vscode-todo-md#70]
Since the latest release 2.20.0 , autocomplete in WebView is broken for Tags, Projects and Contexts

Example: Type "+MyPr" and hit Tab or Enter for autocompletion. Instead of "+MyProject", the following text is entered: [object Object]

Filtering works fine when manually typing "+MyProject"

Thanks a lot!

**Comment by usernamehw** [comment]
Cannot reproduce.

**Comment by enicklas** [comment]
Just tested again:
- Works fine for me if the project filter is the first filter
- Does not work for me (as described above) if there are multiple filters e.g. "$due +MyProject" or "+MyProject #MyTag"
