### ISSUE TITLE
recurring task gets too high priority

### ISSUE THREAD

**Issue by marekbatelka** [usernamehw/vscode-todo-md#79]
It is Thursday, I have recurring task in future (every monday) and I don't want to start or cannot start this task until that date (let's say every monday I have to check something, but cannot before it is really monday).

There seems to be issue, that this recurring task is put first as it would be top priority.

I am thinking if it is on purpose or a bug... 
For such recurring task I could alternatively use Calendar instead, cos any time I try to get next RELEVANT task in queue using command GET next 1 task, or GET next few tasks or looking at toolbar, ordering algorithm offers me this recurring task first.

![image](https://github.com/usernamehw/vscode-todo-md/assets/2838809/ac64ae02-c5a2-46fc-9f30-49eaf0b5bc2d)

**Comment by usernamehw** [comment]
Yeah, it's a default sort slapped everywhere without measure. In `completeTask`, `getNextTask`, `getFewNextTasks`, `status bar` - that's definitely a bug. In WebView - not sure.

They are first grouped and then sorted like that:

1. Overdue group (sort by priority)
1. Due group (sort by priority)
1. Has due but not due group (sort by priority)
1. Doesn't have a due date group (sort by priority)

It should probably go:

1. Overdue group (sort by priority)
1. Due group (sort by priority)
1. "Has due but not due group" & "Doesn't have a due date group" mixed (sort by priority)
