### ISSUE TITLE
Feature Request: Reveal task in editor on click in WebView

### ISSUE THREAD

**Issue by enicklas** [usernamehw/vscode-todo-md#80]
I often use the WebView to find tasks in order to work on them or adjust them in the editor. Currently, I have to right-click -> "Reveal" in order to show the task in the editor. It would be great, if "Reveal" could be (optionally) the default action when clicking on a task in web view.

Thanks for your great work!

**Comment by usernamehw** [comment]
It's already possible if you hold <kbd>Alt</kbd> when clicking.

**Comment by enicklas** [comment]
Ah, perfect, works great! I wasn't aware of that. From my side, this feature request can be closed, the only question is if this should be added to the documentation, either in the README or in the web view UI itself?

**Comment by usernamehw** [comment]
It should be in the docs: https://github.com/usernamehw/vscode-todo-md/blob/master/docs/docs.md#webview-hotkeys

Not sure about Mac keyboards, though... Do they have <kbd>Alt</kbd> key?

**Comment by enicklas** [comment]
I missed that, thanks! Not sure about Macs either, I don't use one.
