### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by enicklas** [usernamehw/vscode-todo-md#81]
I use a keyboard shortcut to set the focus on the web view in order to quickly find or filter tasks. It would be nice if the current text in the web view filter could be (optionally) selected by default on focus on web view, such that I can directly start typing the filter (and overwrite the current filter) after using the keyboard shortcut.

My current workflow is
* Alt - f (my keyboard shortcut to focus on web view)
* Ctr - a
* type the filter

so this feature could remove the middle step. This is just a small issue, but since I use the workflow very often, it would help a lot.

Thanks again!

**Comment by usernamehw** [comment]
I've added 2 arguments to `todomd.focusTasksWebviewAndInput` command:

```js
{
	"key": "ctrl+shift+5",
	"command": "todomd.focusTasksWebviewAndInput",
	"args": {
		"selectInputText": true,
		"fillInputValue": "+error_lens"
	}
}
```

- `selectInputText` - selects all text in input
- `fillInputValue` - updates the text in input to the new value

**Comment by enicklas** [comment]
Great, thanks a lot! Will test after the next release.

**Comment by enicklas** [comment]
Just tested this feature, works perfectly, thanks a lot!
