### ISSUE TITLE
Webview crashes on entering wrong filter

### ISSUE THREAD

**Issue by lin-mbaier** [usernamehw/vscode-todo-md#82]
If you add a wrong filter to the filter field within the webview, the webview crashes. There's no possibilty to clear the filter so that the webview works again.
![image](https://github.com/usernamehw/vscode-todo-md/assets/144340633/1eb74e7d-c661-4e9c-8d5b-3070f24d2045)

This screen is only visible shortly when the webview is minimised:
![image](https://github.com/usernamehw/vscode-todo-md/assets/144340633/f5c95e5f-793a-4909-b17c-49971399136c)

**Comment by usernamehw** [comment]
Maybe "Install another version" menu (previous version) would reset the state for now?

<img width="400" src="https://github.com/usernamehw/vscode-todo-md/assets/9638156/406eda64-2ee1-45c9-9e6d-59b11b9fe7c4">

**Comment by lin-mbaier** [comment]
It works. I installed the previous version. The wrong filter is still in the field, but the webview didn't crash. So I was able to delete the wrong filter. After updating to the current version, it still works.
