### ISSUE TITLE
Using workspaceFolder variable on todomd.defaultFile

### ISSUE THREAD

**Issue by cabello** [usernamehw/vscode-todo-md#87]
Hi there,

I love this extension 💜 , have been using for a while and find it quite handy.

I was expecting this settings would work for me to split to dos between projects without having to have worskpace settings for each one of them:

```
"todomd.defaultFile": "${workspaceFolder}/todo.md",
"todomd.defaultArchiveFile": "${workspaceFolder}/todo.archive.md",
```

**Comment by usernamehw** [comment]
What happens when no workspace opened or multi-root workspace?

**Comment by cabello** [comment]
Good question.

It says the file doesn't exist, then if I create empty files in the expected path, it says the exact same thing.

![CleanShot 2024-01-21 at 12 10 20@2x](https://github.com/usernamehw/vscode-todo-md/assets/60936/aa87f938-8b9a-4fda-b1e4-1b170d028663)
